name: Deploy Ladle to Github Pages

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  deploy:
    name: Deploy Ladle to Github Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Bot
        run: |
          git config --global user.email "services.shared@zig.live"
          git config --global user.name "CDG Zig Bot"

      - name: Setup PNPM
        uses: pnpm/action-setup@v2

      - name: Setup NodeJS 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Build
        run: pnpm run --filter=@comfortdelgro/react-workbench build:ladle

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.CDG_BOT_GITHUB_TOKEN }}
          publish_dir: ./packages/react-workbench/build
          publish_branch: gh-pages/ladle
